import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Toaster } from "react-hot-toast";
import { useAppStore } from "~/store";

const Layout = ({ children }: { children: React.ReactNode }) => {
  const router = useRouter();

  const { setModal } = useAppStore();

  useEffect(() => {
    if (router.query.tx) {
      setModal("PAYMENT");
    }
  }, [router.query, setModal]);

  return (
    <>
      <Head>
        <title>ADA Payment Gateway</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center bg-black px-[5%] font-[helvetica-medium] font-medium leading-6 tracking-wide text-white`}
      >
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              fontFamily: "helvetica-medium",
            },
          }}
        />
        <div className="flex h-auto w-[90vw] max-w-[650px] items-center justify-center">
          {children}
        </div>
      </main>
    </>
  );
};

export default Layout;
